(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



\!\(
\*SubsuperscriptBox[\(T\), \(B\), \(A\)] = \((\*GridBox[{
{
RowBox[{
SubsuperscriptBox["R", "B", "A"], 
RowBox[{(, 
RowBox[{3, *, 3}], )}]}], \[VerticalEllipsis], 
RowBox[{
SuperscriptBox["q", "A"], 
RowBox[{(, 
RowBox[{3, *, 1}], )}]}]},
{\[Ellipsis], \[VerticalEllipsis], \[Ellipsis]},
{
RowBox[{\[Gamma], 
RowBox[{(, 
RowBox[{1, *, 3}], )}]}], \[VerticalEllipsis], 
RowBox[{\[Rho], 
RowBox[{(, 
RowBox[{1, *, 1}], )}]}]}
}])\)\)


RotZ[\[CurlyPhi]_, d_]:= {{Cos[\[CurlyPhi]],-Sin[\[CurlyPhi]],0,0},{Sin[\[CurlyPhi]],Cos[\[CurlyPhi]],0,0},{0,0,1,d},{0,0,0,1}};
RotX[\[CurlyPhi]_, d_]:= {{1,0,0,d},{0,Cos[\[CurlyPhi]],-Sin[\[CurlyPhi]],0},{0,Sin[\[CurlyPhi]],Cos[\[CurlyPhi]],0},{0,0,0,1}};
RotY[\[CurlyPhi]_, d_]:= {{Cos[\[CurlyPhi]],0,-Sin[\[CurlyPhi]],0},{0,0,1,d},{Sin[\[CurlyPhi]],0,Cos[ang],0},{0,0,0,1}};


ConstructDH[{a_,\[Alpha]_,d_,\[Theta]_}]:= RotZ[\[Theta],d].RotX[\[Alpha],a];
MatrixForm[ConstructDH[{a,\[Alpha],d,\[Theta]}]]



